In [1]:
! pip install tensorflow

  Obtaining dependency information for tensorflow from https://files.pythonhosted.org/packages/e4/14/d795bb156f8cc10eb1dcfe1332b7dbb8405b634688980aa9be8f885cc888/tensorflow-2.16.1-cp311-cp311-win_amd64.whl.metadata
  Obtaining dependency information for tensorflow-intel==2.16.1 from https://files.pythonhosted.org/packages/e0/36/6278e4e7e69a90c00e0f82944d8f2713dd85a69d1add455d9e50446837ab/tensorflow_intel-2.16.1-cp311-cp311-win_amd64.whl.metadata
  Obtaining dependency information for absl-py>=1.0.0 from https://files.pythonhosted.org/packages/a2/ad/e0d3c824784ff121c03cc031f944bc7e139a8f1870ffd2845cc2dd76f6c4/absl_py-2.1.0-py3-none-any.whl.metadata
  Obtaining dependency information for astunparse>=1.6.0 from https://files.pythonhosted.org/packages/2b/03/13dde6512ad7b4557eb792fbcf0c653af6076b81e5941d36ec61f7ce6028/astunparse-1.6.3-py2.py3-none-any.whl.metadata
  Obtaining dependency information for flatbuffers>=23.5.26 from https://files.pythonhosted.org/packages/41/f0/7e988a019bc54b2db

In [2]:
! pip install keras

# What is TensorFlow?

Tensorflow (TF) allows intensive machine learning techniques at scale.

### How does it work?

Graphs and sessions. 

Graphs: data structures that hold operations (without calculations) and data. Denoted as a 'graph' because computations can be related to one another. 
Sessions: way to execute computations within a graph. Begins with independent computations and moves on from there.

In [5]:
import tensorflow as tf
print(tf.__version__)

2.16.1


### What is a tensor?

Tensor is a generalization of vectors and matrices to potentially higher dimensions.

Tensors represent partially defined computations that ultimately produce a value. 

Each tensor has a data type and a shape.

data type: floats, ints, strings, etc. 
shape: rerpesentation of the tensor's dimensions.

In [6]:
# Creating tensors takes a value + data type

string = tf.Variable('tensor string', tf.string)
number = tf.Variable(27, tf.int16)
floating = tf.Variable(2.7, tf.float64)

### Rank/Degree

Rank: number of dimensions involved in the tensor. The tensors above are rank 0, aka scalar values.

Rank can be visually determined by the deepest level of a nested list. 

In [8]:
# tensors of higher rank

rank1_tensor = tf.Variable(['test', 'ok','sam'], tf.string) # one dimensional array
rank2_tensor = tf.Variable([['test','ok','sam'],['here','there','everywhere']], tf.string) # two dimensional array / matrix

In [ ]:
print(tf.rank(string))
print(tf.rank(rank1_tensor))
print(tf.rank(rank2_tensor))

### Shape

Shape describes the number of elements in each dimension.

In [14]:
print(tf.shape(rank1_tensor))
print(tf.shape(rank2_tensor)) # two lists with three elements in each

tf.Tensor([3], shape=(1,), dtype=int32)
tf.Tensor([2 3], shape=(2,), dtype=int32)


### Changing shape

Changing shape is a common need. 

Flattening: reducing high dimensional vector down to a single dimension.

In [23]:
tensor1 = tf.ones([1,2,3]) # 1 set of 2 lists containing 3 elements each
print(tensor1)
tensor2 = tf.reshape(tensor1, [2,3,1]) # 2 sets of 3 lists containing 1 element each
print()
print(tensor2)
tensor3 = tf.reshape(tensor2, [3, -1]) # tells tensor to recalculate size of dimension in that place.
                                        # in this case, it will know to make shape 3,2 to return six elements
print()
print(tensor3)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)

tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)

tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


### Types of Tensors

Variable, Constant, Placeholder, SparseTensor.

All tensors are immutable except variable. Use variables when you expect changes.

### Evaluating a Tensor

We will need to obtain tensor values. We run sessions to evaluate tensors. Calling tensor.numpy effectively returns result. 

The default graph holds all operations not specified to any other graphs. It's a good place to start.

In [30]:
tensor = tf.constant([[3, 3, 5],[1, 3, 2]])
evaluated_result = tensor.numpy() # use any tensor to evaluate this
print(evaluated_result)

[[3 3 5]
 [1 3 2]]
